### PR TITLE
Non-ASCII strings get corrupted on round-trip.

### PR DESCRIPTION
**Pull request by asutherland**
Strings get coerced to ASCII by default, which there is no (good) coming back from.

The first push demonstrates the ASCII corruption problem.  The second push seeks to address the problem by explicitly transporting all strings in utf-8 form.

Please let me know if you would like a unit test and/or if I'm doing the pull request wrong.  This is my first pull request!

### CODE REVIEW

**Comment by wadey** [comment]
Good call on this. When I first did the implementation, I wasn't sure what encoding Thrift specified so I left it as ASCII and decided I would revisit. I should have flagged it with a TODO though as it appears I missed it! According to this conversation on this upstream bug, Thrift does indeed specify that strings should be UTF-8: https://issues.apache.org/jira/browse/THRIFT-414

I am currently working on performance branch, I'll make sure that this gets fixed with it. Thanks!

**Comment by asutherland** [comment]
Yeah, your push 2145386d1d42592a5b842fc678f7ce0bd46d9300 should take care of this.  Thanks!

**Comment by Jae** [comment]
Hi We encountered the same issue regarding non-ascii character gets corrupted on master branch.

We could use performance branch, but tagomoris's BufferedTransport is missing from performance branch which we need to talk to our Hive server.

Any plan of merging performance branch into master or tagomoris's checkin into performance branch?

**Comment by wadey** [comment]
Yeah, my plan is to merge those soon, hopefully this week.

**Comment by kompiro** [comment]
Is this contained in 0.7.0 release?
I test it at 0.7.0 release and performance branch, this issue is still occurred...

**Comment by bobrik** [comment]
This is not in master, only in performance branch. Should be merged to master. Really

**Comment by wadey** [comment]
I started this merge last weekend. It will be in by 0.8 for sure.

**Comment by wadey** [comment]
I merged node-thrift 0.7.0 with my performance branch, and plan to merge into node-thrift 0.8.0-dev. Can I get a few people to test this?
- `thrift-dev` on npm
- https://github.com/wadey/node-thrift/tree/performance

You will need this compiler patch:

https://issues.apache.org/jira/browse/THRIFT-1351

Two non-backwords compatible changes:
- "binary" fields will be returned as Buffers instead of Strings
- "int64" fields will be returned as http://github.com/broofa/node-int64 objects

**Comment by kompiro** [comment]
I tested the thrift-dev and this exception is thrown below.

xxx/node_modules/evernode/lib/evernode/CustomConnections.js:64
        throw e;
        ^
TypeError: Object #<Object> has no method 'readI32'
    at [object Object].readI32 (xxx/node_modules/thrift/lib/thrift/protocol.js:264:21)
    at [object Object].readMessageBegin (xxx/node_modules/thrift/lib/thrift/protocol.js:173:17)
    at ***/node_modules/evernode/lib/evernode/CustomConnections.js:44:28

I use evernode [https://github.com/flyingninjasquirrel/evernode] and evernode uses TBufferedTransport (by default setting).

TFramedTransport has readI32. So I changed to use TFramedTransport, but buffering error has occurred...

**Comment by wadey** [comment]
Ah yes, I can see the problem with TBufferedTransport. I will get a fix committed for this.

**Comment by wadey** [comment]
I have pushed a fix for TBufferedTransport and updated thrift-dev in npm to 0.8.0-dev02.

**Comment by kompiro** [comment]
Thanks! The my reported error hasn't occurred and the original issues doesn't occurred now! 
So if I get some error, I'll create another issue.

**Comment by bobrik** [comment]
It's ok with node-scribe module now

**Pull request closed without merging**
